(function () {
  const CATEGORY_LIST = [
    { id: "ent_video", label: "エンターテイメント / 動画", keywords: ["video", "movie", "youtube", "ニコニコ", "配信", "動画"] },
    { id: "ent_music", label: "エンターテイメント / 音楽", keywords: ["music", "spotify", "sound", "音楽", "歌", "band"] },
    { id: "ent_stream", label: "エンターテイメント / ライブ配信", keywords: ["live", "stream", "twitch", "ライブ", "配信"] },
    { id: "ent_anime", label: "エンターテイメント / アニメ", keywords: ["anime", "アニメ", "animation"] },
    { id: "ent_manga", label: "エンターテイメント / マンガ", keywords: ["manga", "comic", "マンガ", "漫画"] },
    { id: "ent_movie", label: "エンターテイメント / 映画", keywords: ["movie", "cinema", "film", "映画"] },
    { id: "ent_tv", label: "エンターテイメント / テレビ", keywords: ["tv", "テレビ", "broadcast"] },
    { id: "ent_theater", label: "エンターテイメント / 舞台", keywords: ["theater", "舞台", "演劇"] },
    { id: "ent_idol", label: "エンターテイメント / アイドル", keywords: ["idol", "アイドル"] },
    { id: "ent_radio", label: "エンターテイメント / ラジオ", keywords: ["radio", "ラジオ"] },
    { id: "edu_elearning", label: "学習 / eラーニング", keywords: ["elearning", "e-learning", "学習", "講座", "授業"] },
    { id: "edu_research", label: "学習 / 研究", keywords: ["research", "研究", "論文"] },
    { id: "edu_dictionary", label: "学習 / 辞書", keywords: ["dictionary", "辞書", "辞典"] },
    { id: "edu_language", label: "学習 / 語学", keywords: ["language", "英語", "語学", "辞書"] },
    { id: "edu_coding", label: "学習 / プログラミング", keywords: ["code", "coding", "program", "プログラミング", "開発"] },
    { id: "edu_math", label: "学習 / 数学", keywords: ["math", "数学", "算数"] },
    { id: "edu_science", label: "学習 / 理科", keywords: ["science", "理科", "化学", "物理", "生物"] },
    { id: "edu_history", label: "学習 / 歴史", keywords: ["history", "歴史", "世界史", "日本史"] },
    { id: "edu_exam", label: "学習 / 受験", keywords: ["exam", "test", "受験", "試験"] },
    { id: "edu_teacher", label: "学習 / 教師向け", keywords: ["teacher", "教育", "指導", "教材"] },
    { id: "news_general", label: "ニュース / 総合", keywords: ["news", "ニュース", "press"] },
    { id: "news_local", label: "ニュース / 地域", keywords: ["local", "地域", "市", "町"] },
    { id: "news_world", label: "ニュース / 国際", keywords: ["world", "international", "国際"] },
    { id: "news_politics", label: "ニュース / 政治", keywords: ["politics", "政治", "政党", "選挙"] },
    { id: "news_economy", label: "ニュース / 経済", keywords: ["economy", "経済", "株", "金融"] },
    { id: "news_weather", label: "ニュース / 天気", keywords: ["weather", "天気", "気象"] },
    { id: "news_disaster", label: "ニュース / 災害", keywords: ["disaster", "災害", "地震", "台風"] },
    { id: "news_sports", label: "ニュース / スポーツ", keywords: ["sports", "スポーツ"] },
    { id: "news_education", label: "ニュース / 教育", keywords: ["education", "教育", "学校"] },
    { id: "news_tech", label: "ニュース / IT", keywords: ["tech", "technology", "IT", "テック"] },
    { id: "sns_microblog", label: "SNS / マイクロブログ", keywords: ["twitter", "x.com", "mastodon", "microblog"] },
    { id: "sns_photo", label: "SNS / 写真", keywords: ["instagram", "photo", "写真"] },
    { id: "sns_video", label: "SNS / 動画SNS", keywords: ["tiktok", "shorts", "リール", "video"] },
    { id: "sns_chat", label: "SNS / チャット", keywords: ["chat", "messenger", "ライン", "line"] },
    { id: "sns_community", label: "SNS / コミュニティ", keywords: ["community", "掲示板", "forum", "sns"] },
    { id: "sns_forum", label: "SNS / フォーラム", keywords: ["forum", "bbs", "掲示板"] },
    { id: "sns_blog", label: "SNS / ブログ", keywords: ["blog", "ブログ"] },
    { id: "sns_live", label: "SNS / ライブ配信", keywords: ["live", "stream", "配信"] },
    { id: "sns_voice", label: "SNS / 音声通話", keywords: ["voice", "discord", "通話"] },
    { id: "sns_dating", label: "SNS / マッチング", keywords: ["dating", "match", "出会い"] },
    { id: "game_console", label: "ゲーム / コンソール", keywords: ["switch", "playstation", "xbox", "console"] },
    { id: "game_pc", label: "ゲーム / PC", keywords: ["pc game", "steam", "game"] },
    { id: "game_mobile", label: "ゲーム / モバイル", keywords: ["mobile game", "app game", "スマホ"] },
    { id: "game_browser", label: "ゲーム / ブラウザ", keywords: ["browser game", "flash", "game"] },
    { id: "game_esports", label: "ゲーム / eスポーツ", keywords: ["esports", "eスポーツ"] },
    { id: "game_news", label: "ゲーム / ニュース", keywords: ["game news", "ゲームニュース"] },
    { id: "game_community", label: "ゲーム / コミュニティ", keywords: ["game forum", "guild", "クラン"] },
    { id: "game_mod", label: "ゲーム / MOD", keywords: ["mod", "改造"] },
    { id: "game_stream", label: "ゲーム / 配信", keywords: ["stream", "twitch", "配信"] },
    { id: "game_strategy", label: "ゲーム / 攻略", keywords: ["攻略", "walkthrough"] },
    { id: "shop_market", label: "ショッピング / 総合EC", keywords: ["shop", "shopping", "楽天", "amazon"] },
    { id: "shop_auction", label: "ショッピング / オークション", keywords: ["auction", "オークション"] },
    { id: "shop_food", label: "ショッピング / フードデリバリ", keywords: ["delivery", "food", "フード"] },
    { id: "shop_fashion", label: "ショッピング / ファッション", keywords: ["fashion", "apparel", "服"] },
    { id: "shop_electronics", label: "ショッピング / 家電", keywords: ["electronics", "電機", "家電"] },
    { id: "shop_books", label: "ショッピング / 書籍", keywords: ["book", "書籍", "本"] },
    { id: "shop_ticket", label: "ショッピング / チケット", keywords: ["ticket", "チケット"] },
    { id: "shop_coupon", label: "ショッピング / クーポン", keywords: ["coupon", "クーポン"] },
    { id: "shop_subscribe", label: "ショッピング / サブスク", keywords: ["subscription", "サブスク"] },
    { id: "shop_travel", label: "ショッピング / 旅行予約", keywords: ["booking", "travel", "予約"] },
    { id: "life_health", label: "生活/健康 / 健康", keywords: ["health", "健康", "病院"] },
    { id: "life_medical", label: "生活/健康 / 医療", keywords: ["medical", "clinic", "医療", "診療"] },
    { id: "life_fitness", label: "生活/健康 / フィットネス", keywords: ["fitness", "workout", "運動"] },
    { id: "life_diet", label: "生活/健康 / 食事", keywords: ["diet", "料理", "レシピ", "食事"] },
    { id: "life_mental", label: "生活/健康 / メンタル", keywords: ["mental", "カウンセリング", "メンタル"] },
    { id: "life_parenting", label: "生活/健康 / 子育て", keywords: ["parent", "育児", "子育て"] },
    { id: "life_home", label: "生活/健康 / 住まい", keywords: ["home", "house", "不動産"] },
    { id: "life_cooking", label: "生活/健康 / 料理", keywords: ["cook", "recipe", "料理"] },
    { id: "life_finance", label: "生活/健康 / 家計", keywords: ["budget", "家計", "家計簿"] },
    { id: "life_insurance", label: "生活/健康 / 保険", keywords: ["insurance", "保険"] },
    { id: "biz_office", label: "仕事/ビジネス / オフィス", keywords: ["office", "excel", "docs"] },
    { id: "biz_hr", label: "仕事/ビジネス / 人事", keywords: ["hr", "recruit", "採用"] },
    { id: "biz_marketing", label: "仕事/ビジネス / マーケティング", keywords: ["marketing", "広告", "campaign"] },
    { id: "biz_sales", label: "仕事/ビジネス / 営業", keywords: ["sales", "営業"] },
    { id: "biz_crm", label: "仕事/ビジネス / CRM", keywords: ["crm", "customer"] },
    { id: "biz_accounting", label: "仕事/ビジネス / 会計", keywords: ["accounting", "会計", "経理"] },
    { id: "biz_project", label: "仕事/ビジネス / プロジェクト管理", keywords: ["project", "管理", "kanban"] },
    { id: "biz_remote", label: "仕事/ビジネス / リモート", keywords: ["remote", "zoom", "meet", "会議"] },
    { id: "biz_productivity", label: "仕事/ビジネス / 生産性", keywords: ["productivity", "タスク", "todo"] },
    { id: "biz_enterprise", label: "仕事/ビジネス / 企業向け", keywords: ["enterprise", "法人"] },
    { id: "it_cloud", label: "技術/IT / クラウド", keywords: ["cloud", "aws", "azure", "gcp"] },
    { id: "it_storage", label: "技術/IT / ストレージ", keywords: ["drive", "dropbox", "storage", "box.com", "ストレージ"] },
    { id: "it_devtools", label: "技術/IT / 開発ツール", keywords: ["github", "gitlab", "dev", "tool"] },
    { id: "it_security", label: "技術/IT / セキュリティ", keywords: ["security", "sec", "脆弱", "ウイルス"] },
    { id: "it_ai", label: "技術/IT / AI", keywords: ["ai", "ml", "artificial", "機械学習"] },
    { id: "it_data", label: "技術/IT / データ", keywords: ["data", "database", "db", "分析"] },
    { id: "it_hardware", label: "技術/IT / ハード", keywords: ["hardware", "pc", "cpu", "gpu"] },
    { id: "it_network", label: "技術/IT / ネットワーク", keywords: ["network", "router", "wifi"] },
    { id: "it_open", label: "技術/IT / オープンソース", keywords: ["open source", "oss"] },
    { id: "it_hosting", label: "技術/IT / ホスティング", keywords: ["hosting", "server", "vps"] },
    { id: "risk_adult", label: "リスク/有害 / 成人向け", keywords: ["adult", "porn", "アダルト", "18+"] },
    { id: "risk_gambling", label: "リスク/有害 / ギャンブル", keywords: ["casino", "bet", "poker", "ギャンブル", "競馬"] },
    { id: "risk_violence", label: "リスク/有害 / 暴力", keywords: ["violence", "weapon", "暴力", "武器", "銃"] },
    { id: "risk_drugs", label: "リスク/有害 / 薬物", keywords: ["drug", "cannabis", "薬物", "大麻"] },
    { id: "risk_selfharm", label: "リスク/有害 / 自傷", keywords: ["self harm", "自傷", "自殺"] },
    { id: "risk_crime", label: "リスク/有害 / 犯罪", keywords: ["crime", "犯罪", "詐欺"] },
    { id: "risk_hacking", label: "リスク/有害 / ハッキング", keywords: ["hack", "hacking", "不正"] },
    { id: "risk_piracy", label: "リスク/有害 / 海賊版", keywords: ["torrent", "piracy", "海賊版"] },
    { id: "risk_malware", label: "リスク/有害 / マルウェア", keywords: ["malware", "virus", "ウイルス"] },
    { id: "risk_bullying", label: "リスク/有害 / いじめ", keywords: ["bully", "いじめ"] }
  ];

  const CATEGORY_KEYWORDS = {};
  CATEGORY_LIST.forEach((item) => {
    if (item.keywords && item.keywords.length > 0) {
      CATEGORY_KEYWORDS[item.id] = item.keywords;
    }
  });

  const root = typeof window !== "undefined" ? window : self;
  root.MSEFILTER_CATEGORIES = { list: CATEGORY_LIST, keywords: CATEGORY_KEYWORDS };
})();
